_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/faster_rcnn_R_50_FPN_1x/137257794/model_final_b275ba.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
    NAME: "StandardROIHeads"
OUTPUT_DIR: "pdd_union_out/"
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  STEPS: (400, 900)
  MAX_ITER: 1500
